services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
      target: frontend
    image: tlandart/quirknotes_frontend:latest
    ports:
      - "3000:80"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    image: tlandart/quirknotes_backend:latest
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"